<?php

class Constants {
	
	/*
	 * Clase edad sexo
	 */
	const CLASE_EDAD_SEXO_INDETERMINADO_ID = 4;
	
	/*
	 * Menu
	 */
	const MENU_INICIO_ID = 1;
	const MENU_CITAS_ID = 2;
	const MENU_ESPECIE_ID = 3;
	const MENU_LOCALIZACION_ID = 4;
	const MENU_OBSERVADORES_ID = 5;
	const MENU_ACERCA_DE_ID = 6;
	const MENU_AYUDA_ID = 7;
	
	/*
	 * Importancia
	 */
	const IMPORTANCIA_RAREZA_NACIONAL_ID = 1;
	const IMPORTANCIA_RAREZA_LOCAL_ID = 2;
	const IMPORTANCIA_ESP_PROTEGIDA_ID = 3;
	const IMPORTANCIA_ESP_MUY_ESCASA_ID = 4;
	const IMPORTANCIA_RAREZA_NAC_CRIA_PROBABLE_ID = 5;
	const IMPORTANCIA_RAREZA_LOCAL_CRIA_PROBABLE_ID = 6;
	const IMPORTANCIA_ESP_PROTEGIDA_CRIA_PROBABLE_ID = 7;
	const IMPORTANCIA_ESP_ESCASA_CRIA_PROBABLE_ID = 8;
	const IMPORTANCIA_RAREZA_NAC_CRIA_SEGURA_ID = 9;
	const IMPORTANCIA_RAREZA_LOCAL_CRIA_SEGURA_ID = 10;
	const IMPORTANCIA_ESP_PROTEGIDA_CRIA_SEGURA_ID = 11;
	const IMPORTANCIA_ESP_ESCASA_CRIA_SEGURA_ID = 12;
	const IMPORTANCIA_NO_DESTACADO_ID = 13;
	
	/*
	 * Privacidad
	 */
	const PRIVACIDAD_COMPORTAMIENTO_REPRODUCTIVO = 1;
	const PRIVACIDAD_PERIODO_1MAYO_31AGOSTO = 2;
	const PRIVACIDAD_PERIODO_1MAYO_31JULIO = 3;
	const PRIVACIDAD_PERIODO_1ENERO_31DICIEMBRE = 4;
	const PRIVACIDAD_PERIODO_1ABRIL_31AGOSTO = 5;
	const PRIVACIDAD_PERIODO_1ABRIL_31JULIO = 6;
	const PRIVACIDAD_PERIODO_1FEBRERO_31JULIO = 7;
	const PRIVACIDAD_PERIODO_1MARZO_31AGOSTO = 8;
	const PRIVACIDAD_PERIODO_1MARZO_31JULIO = 9;
	const PRIVACIDAD_PERIODO_1ENERO_31JULIO = 10;
	const PRIVACIDAD_PERIODO_1MARZO_30JUNIO = 11;
	const PRIVACIDAD_CUALQUIER_SEXO_EDAD = 12;
	const PRIVACIDAD_SEXO_HEMBRA_CUALQUIER_EDAD = 13;
	const PRIVACIDAD_SEXO_MACHO_CUALQUIER_EDAD = 14;
	const PRIVACIDAD_EDAD_ADULTA_CUALQUIER_SEXO = 15;
	
	/*
	 * Meses
	 */
	const ENERO = 1;
	const FEBRERO = 2;
	const MARZO = 3;
	const ABRIL = 4;
	const MAYO = 5;
	const JUNIO = 6;
	const JULIO = 7;
	const AGOSTO = 8;
	const SEPTIEMBRE = 9;
	const OCTUBRE = 10;
	const NOVIEMBRE = 11;
	const DICIEMBRE = 12;
	
	
}

?>