ALTER TABLE `cowctkq_familia` ADD COLUMN `posicion` int(4) NULL COMMENT 'Posición por la que se deberían de ordenar las familias taxonómicamente';

INSERT INTO  `cowctkq_familia` VALUES (90,'Oceanitidae',16, 6,1);
INSERT INTO  `cowctkq_familia` VALUES (91,'Pluvianidae',57, 13,1);
INSERT INTO  `cowctkq_familia` VALUES (92,'Malaconotidae',142, 24,1);
INSERT INTO  `cowctkq_familia` VALUES (93,'Panuridae',180, 24,1);
INSERT INTO  `cowctkq_familia` VALUES (94,'Scotocercidae',187, 24,1);
INSERT INTO  `cowctkq_familia` VALUES (95,'Phylloscopidae',191, 24,1);
INSERT INTO  `cowctkq_familia` VALUES (96,'Acrocephalidae',192, 24,1);
INSERT INTO  `cowctkq_familia` VALUES (97,'Locustellidae',193, 24,1);
INSERT INTO  `cowctkq_familia` VALUES (98,'Cisticolidae',196, 24,1);
INSERT INTO  `cowctkq_familia` VALUES (99,'Leiothrichidae',199, 24,1);
INSERT INTO  `cowctkq_familia` VALUES (100,'Regulidae',205, 24,1);
INSERT INTO  `cowctkq_familia` VALUES (101,'Calcariidae',231, 24,1);

UPDATE `cowctkq_familia` SET `id` = 2 WHERE `posicion` = 8;
UPDATE `cowctkq_familia` SET `id` = 4 WHERE `posicion` = 13;
UPDATE `cowctkq_familia` SET `id` = 6 WHERE `posicion` = 14;
UPDATE `cowctkq_familia` SET `id` = 7 WHERE `posicion` = 20;
UPDATE `cowctkq_familia` SET `id` = 8 WHERE `posicion` = 17;
UPDATE `cowctkq_familia` SET `id` = 9 WHERE `posicion` = 19;
UPDATE `cowctkq_familia` SET `id` = 10 WHERE `posicion` = 18;
UPDATE `cowctkq_familia` SET `id` = 11 WHERE `posicion` = 22;
UPDATE `cowctkq_familia` SET `id` = 12 WHERE `posicion` = 30;
UPDATE `cowctkq_familia` SET `id` = 13 WHERE `posicion` = 31;
UPDATE `cowctkq_familia` SET `id` = 15 WHERE `posicion` = 28;
UPDATE `cowctkq_familia` SET `id` = 16 WHERE `posicion` = 29;
UPDATE `cowctkq_familia` SET `id` = 17 WHERE `posicion` = 25;
UPDATE `cowctkq_familia` SET `id` = 18 WHERE `posicion` = 23;
UPDATE `cowctkq_familia` SET `id` = 19 WHERE `posicion` = 24;
UPDATE `cowctkq_familia` SET `id` = 20 WHERE `posicion` = 21;
UPDATE `cowctkq_familia` SET `id` = 21 WHERE `posicion` = 36;
UPDATE `cowctkq_familia` SET `id` = 22 WHERE `posicion` = 35;
UPDATE `cowctkq_familia` SET `id` = 23 WHERE `posicion` = 104;
UPDATE `cowctkq_familia` SET `id` = 24 WHERE `posicion` = 44;
UPDATE `cowctkq_familia` SET `id` = 25 WHERE `posicion` = 48;
UPDATE `cowctkq_familia` SET `id` = 26 WHERE `posicion` = 46;
UPDATE `cowctkq_familia` SET `nombre` = 'Otididae', `posicion` = 37 WHERE `nombre` = 'Otidae';
UPDATE `cowctkq_familia` SET `id` = 29 WHERE `posicion` = 52;
UPDATE `cowctkq_familia` SET `id` = 30 WHERE `posicion` = 55;
UPDATE `cowctkq_familia` SET `id` = 32 WHERE `posicion` = 49;
UPDATE `cowctkq_familia` SET `id` = 33 WHERE `posicion` = 63;
UPDATE `cowctkq_familia` SET `id` = 34 WHERE `posicion` = 56;
UPDATE `cowctkq_familia` SET `id` = 35 WHERE `posicion` = 62;
UPDATE `cowctkq_familia` SET `id` = 36 WHERE `posicion` = 65;
UPDATE `cowctkq_familia` SET `id` = 37 WHERE `posicion` = 64;
UPDATE `cowctkq_familia` SET `id` = 40 WHERE `posicion` = 66;
UPDATE `cowctkq_familia` SET `nombre` = 'Pteroclidae', `posicion` = 67 WHERE `nombre` = 'Pteroclididae';
UPDATE `cowctkq_familia` SET `id` = 42 WHERE `posicion` = 68;
UPDATE `cowctkq_familia` SET `id` = 43 WHERE `posicion` = 107;
UPDATE `cowctkq_familia` SET `id` = 44 WHERE `posicion` = 71;
UPDATE `cowctkq_familia` SET `id` = 45 WHERE `posicion` = 72;
UPDATE `cowctkq_familia` SET `id` = 46 WHERE `posicion` = 73;
UPDATE `cowctkq_familia` SET `id` = 47 WHERE `posicion` = 77;
UPDATE `cowctkq_familia` SET `id` = 48 WHERE `posicion` = 80;
UPDATE `cowctkq_familia` SET `id` = 50 WHERE `posicion` = 87;
UPDATE `cowctkq_familia` SET `id` = 51 WHERE `posicion` = 90;
UPDATE `cowctkq_familia` SET `id` = 52 WHERE `posicion` = 85;
UPDATE `cowctkq_familia` SET `id` = 53 WHERE `posicion` = 91;
UPDATE `cowctkq_familia` SET `id` = 54 WHERE `posicion` = 103;
UPDATE `cowctkq_familia` SET `id` = 56 WHERE `posicion` = 181;
UPDATE `cowctkq_familia` SET `id` = 57 WHERE `posicion` = 183;
UPDATE `cowctkq_familia` SET `id` = 58 WHERE `posicion` = 228;
UPDATE `cowctkq_familia` SET `id` = 59 WHERE `posicion` = 182;
UPDATE `cowctkq_familia` SET `id` = 60 WHERE `posicion` = 170;
UPDATE `cowctkq_familia` SET `id` = 61 WHERE `posicion` = 218;
UPDATE `cowctkq_familia` SET `id` = 62 WHERE `posicion` = 208;
UPDATE `cowctkq_familia` SET `id` = 63 WHERE `posicion` = 213;
UPDATE `cowctkq_familia` SET `id` = 64 WHERE `posicion` = 227;
UPDATE `cowctkq_familia` SET `id` = 65 WHERE `posicion` = 216;
UPDATE `cowctkq_familia` SET `id` = 66 WHERE `posicion` = 200;
UPDATE `cowctkq_familia` SET `id` = 67 WHERE `posicion` = 217;
UPDATE `cowctkq_familia` SET `id` = 69 WHERE `posicion` = 190;
UPDATE `cowctkq_familia` SET `id` = 70 WHERE `posicion` = 177;
UPDATE `cowctkq_familia` SET `id` = 71 WHERE `posicion` = 210;
UPDATE `cowctkq_familia` SET `id` = 72 WHERE `posicion` = 211;
UPDATE `cowctkq_familia` SET `id` = 73 WHERE `posicion` = 212;
UPDATE `cowctkq_familia` SET `id` = 74 WHERE `posicion` = 178;
UPDATE `cowctkq_familia` SET `id` = 76 WHERE `posicion` = 157;
UPDATE `cowctkq_familia` SET `id` = 77 WHERE `posicion` = 155;
UPDATE `cowctkq_familia` SET `id` = 79 WHERE `posicion` = 161;
UPDATE `cowctkq_familia` SET `id` = 80 WHERE `posicion` = 214;
UPDATE `cowctkq_familia` SET `id` = 81 WHERE `posicion` = 222;
UPDATE `cowctkq_familia` SET `id` = 82 WHERE `posicion` = 223;
UPDATE `cowctkq_familia` SET `id` = 83 WHERE `posicion` = 224;
UPDATE `cowctkq_familia` SET `id` = 84 WHERE `posicion` = 156;
UPDATE `cowctkq_familia` SET `id` = 85 WHERE `posicion` = 230;
UPDATE `cowctkq_familia` SET `id` = 86 WHERE `posicion` = 243;
UPDATE `cowctkq_familia` SET `id` = 88 WHERE `posicion` = 233;
UPDATE `cowctkq_familia` SET `id` = 89 WHERE `posicion` = 242;
